name: testing
on: [push, pull_request]

jobs:
  tests:
    name: Test on ${{ matrix.os }} (v${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest, macos-latest
        node: [12, 14, 16]
        include:
          - name: Linux
            os: ubuntu-latest
          # - name: Windows
          #   os: windows-latest
          # - name: macOS
          #   os: macos-latest
    steps:
      - name: Pull source
        uses: actions/checkout@master
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup a node
        run: git clone https://github.com/Robin-floss/rstorage-node/ && cd rstorage-node && cp .env.example .env && npm install && npm start && cp keys/node.cert ../
      - name: Install dependencies
        run: npm install
      - name: Setup environment
        run: cp .env.example .env
      - name: Run TestCafe Tests
        run: if [ "$RUNNER_OS" == "Linux" ]; then npm run ci-test-linux; elif [ "$RUNNER_OS" == "Windows" ]; then npm run ci-test-windows; elif [ "$RUNNER_OS" == "macOS" ]; then npm run ci-test-mac; fi
        shell: bash